#!/bin/bash

# Main programm for merge or shelling sub programms 

# Where is this project
PR_DIR="$HOME/Projects/librarian"
if [ ! -d $PR_DIR ]; then
	echo "Error project dir doesn't exist" >&2
	exit 1
fi
# Help or usage message
usage () {
	cat <<- _EOF_
	Usage: libraryan [OPTION]...
	Manage and tags a files with the type
	
	  -i, --interactive		turn on interactive mode
	  -h, --help			show this message
	  -t, --transfer		transfer [and unzip] the files from gather dir in buffer dir
	  -m, --tag, --mark		tags and write in hystory files and move them in topics dir
	  --config			open config file to change
	_EOF_
	return
}

# For saccess meseges
suc_mes () {
	if [ $? -eq 0 ]; then
        	echo $1
	fi
}


# If no arguments, start interactive mod
if [[ ! -n $1 ]]; then
	bash $PR_DIR/librarian --interactive
fi

# Processing shels parametrs
interactive=

while [[ -n $1 ]]; do
	case $1 in 
		-i | --interactive)	interactive=1
					;;
		-h | --help)		usage
					exit
					;;
		-t | --transfer)	bash $PR_DIR/transfer.sh
					suc_mes "Transfer was success"
					;;
		-m | --tag | --mark)	bash $PR_DIR/tags.sh
					suc_mes "Taging was complete"
					;;
		--config)		vim $PR_DIR/.config
					suc_mes "Config file was opened"
					exit
					;;
		*)			usage >&2
					exit 1
					;;
	esac
	shift
done

# Interactive mod

comands () {
        cat <<- _EOF_
	Comands:

	1, h, help		show this message
	2, d, do		transfer and then mark the files
	3, t, transfer		transfer [and unzip] the files from gather dir in buffer dir
	4, m, tag, mark		tags and write in hystory files and move them in topics dir
	5, config		open config file to change
	0, q, Q			quit the program
	_EOF_
}

if [[ -n $interactive ]]; then
	comands
	while true; do
		echo "Enter (q|Q|0) for exit, (h|help|1) to show comands"
		read -p "Enter comand -> "
		case $REPLY in
			0|Q|q)		echo "Program terminated."
					exit
					;;
			1|h|help)	comands
					continue
					;;
			2|d|do)		bash $PR_DIR/librarian --transfer --tag
					continue
					;;
			3|t|transfer)	bash $PR_DIR/librarian --transfer
					continue
					;;
			4|m|tag|mark)	bash $PR_DIR/librarian --tag
					continue
					;;
			5|config)	bash $PR_DIR/librarian --config
					continue
					;;
			*)		echo "This commant is not exist"
					continue
					;;
		esac
	done
fi
